kumuluzee:
  name: vehicle-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/VehicleDS
      connection-url: jdbc:postgresql://localhost:5432/vehicles
      username: dbuser
      password: postgres
      max-pool-size: 20
  health:
    checks:
      data-source-health-checks:
        jndi-name: jdbc/VehicleDS
        type: liveness
      disk-space-health-check:
        threshold: 100000000
      http-health-check:
        connection-url: https://www.google.com/
#    metrics:
#      web-instrumentation:
#        - name: vehicles-endpoint
#          url-pattern: /v1/vehicles/*
  metrics:
    web-instrumentation:
      - name: vehicles-endpoint
        url-pattern: /v1/vehicles/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                          <Configuration name="comments">
                              <Appenders>
                                  <Console name="console" target="SYSTEM_OUT">
                                      <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                  </Console>
                                  <Socket name="logstash" host="707a9b69-5203-4416-a606-408efead7b29-ls.logit.io"
                                  port="23759" protocol="udp">
                                      <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                  </Socket>
                              </Appenders>
                              <Loggers>
                                  <!-- Default logger -->
                                  <Root level="all">
                                      <AppenderRef ref="console" level="info" />
                                      <AppenderRef ref="logstash" level="trace" />
                                  </Root>
                              </Loggers>
                          </Configuration>'
  cors-filter:
    annotations:
      my-resource:
        allow-origin: "*"
        allow-subdomains: true
        supported-methods: "GET, POST, HEAD, OPTIONS, PUT, DELETE"


rest-properties:
  maintenance-mode: false
  broken: false